{"name": "test_add_image", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'D:\\\\aaa.png'", "trace": "login_xadmin_fix = <requests.sessions.Session object at 0x0000000004C7E470>\ndel_image = None\n\n    def test_add_image(login_xadmin_fix, del_image):\n        url = os.environ['xadmin_host'] + '/xadmin/hello/fileimage/add/'\n        res = login_xadmin_fix.get(url)\n        token = re.findall(\"name='csrfmiddlewaretoken' value='(.+?)'\", res.text)\n        data = MultipartEncoder(\n            fields=[\n                (\"csrfmiddlewaretoken\", token[0]),\n                (\"csrfmiddlewaretoken\", token[0]),\n                (\"title\", \"file_image_001\"),\n>               (\"image\", (\"aaa.png\", open(\"D:\\\\aaa.png\", \"rb\"), \"image/png\")),\n                (\"fiels\", (\"pom.xml\", open(\"D:\\\\AutoTest\\\\pom.xml\", \"rb\"), \"image/png\")),\n                (\"_save\", \"\")\n            ]\n        )\nE       FileNotFoundError: [Errno 2] No such file or directory: 'D:\\\\aaa.png'\n\ncase\\xadmin_login\\test_image_add.py:16: FileNotFoundError"}, "attachments": [{"name": "stdout", "source": "2c41eec2-9303-4e25-92b6-6195f8e2ddae-attachment.txt", "type": "text/plain"}], "start": 1579143929876, "stop": 1579143929969, "uuid": "a68a9dc3-64f2-41ae-b125-1ff5dfd2b680", "historyId": "02051fd89fed383f1ceb268e514fb652", "testCaseId": "aee3a7422a2fb156ad22c274ff49e9f3", "fullName": "case.xadmin_login.test_image_add#test_add_image", "labels": [{"name": "parentSuite", "value": "case.xadmin_login"}, {"name": "suite", "value": "test_image_add"}, {"name": "host", "value": "BF100430"}, {"name": "thread", "value": "13068-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.xadmin_login.test_image_add"}]}